### ISSUE TITLE
Doc: Configuration route_schema per type and template

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/SuluArticleBundle#218]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| SuluArticleBundle Version | 0.6
| Sulu Version | noen

#### Expected Behavior

Missing documentation for `route_schema` per `type` or template.

```yaml
sulu_route:
    mappings:
        Sulu\Bundle\ArticleBundle\Document\ArticleDocument:
            generator: type
            options:
                article: "/artikel/{object.getTitle()}"
                gallery: "/galerie/{object.getTitle()}"
```
