### ISSUE TITLE
Focussing the route field results in it being submitted in POST empty

### ISSUE THREAD

**Issue by matt-halliday** [sulu/SuluArticleBundle#230]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 0.6.1
| Sulu Version | 1.6.1

#### Actual Behavior

```
Given I am creating a new article
And I leave the "route" field empty
When I save the article
Then the article has no route
And I cannot edit the route
```

#### Expected Behavior

```
Given I am creating a new article
And I leave the "route" field empty
When I save the article
Then the article has a route
And I can edit the route
```

#### Steps to Reproduce
n.b. I am using Chrome `60.0.3112.78 (Official Build) (64-bit)`

1. Add config to generate routes based on type or template. e.g.:
```
sulu_route:
    mappings:
        Sulu\Bundle\ArticleBundle\Document\ArticleDocument:
            generator: template
            options:
                article_default: "/news/{object.getTitle()}"
```
2. Create a new document - use tab to go through the fields, tabbing over the route field to leave it empty though focused at one point.
3. Save Draft

#### Possible Solutions
Trim the input of the route field before adding it to post data? Not sure if there's some javascript trying to add values in here on validation of empty field.
