### ISSUE TITLE
Url History not working when extending ArticleDocument

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluArticleBundle#370]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 1.0.1
| Sulu Version | 1.6.24

#### Actual Behavior

Url History not working when extending ArticleDocument.

#### Expected Behavior

Url Histroy should work.

#### Steps to Reproduce

Extend the ArticleDocument:

```yml
sulu_document_manager:
    mapping:
        article:
            class: AppBundle\Document\ArticleDocument
            phpcr_type: "sulu:article"
        article_page:
            class: AppBundle\Document\ArticlePageDocument
            phpcr_type: "sulu:articlepage"
            form_type: AppBundle\Document\Form\ArticlePageDocumentType

sulu_route:
    mappings:
        Sulu\Bundle\ArticleBundle\Document\ArticleDocument:
            className: AppBundle\Document\ArticleDocument
            generator: schema
            options:
                route_schema: "/{object.getTitle()}"
        Sulu\Bundle\ArticleBundle\Document\ArticlePageDocument:
            className: AppBundle\Document\ArticlePageDocument
            generator: article_page
            options:
                route_schema: "/page/{object.getPageNumber()}"
                parent: "{object.getParent().getRoutePath()}"
```

The url history is not working because of hardcoded class in js:

https://github.com/sulu/SuluArticleBundle/blob/1.0.1/Resources/public/js/components/articles/edit/details/main.js#L200

#### Possible Solutions

This value should not be hardcoded
