### ISSUE TITLE
Wrong Route Translation when adding new Article

### ISSUE THREAD

**Issue by marcostastny** [sulu/SuluArticleBundle#432]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | 0b8f7b6f9876b63dd38262a99b487d57754aa8db
| Sulu Version | 2.0.3

#### Actual Behavior

When adding a new article it will take the route schema from the configured system language instead of the template language i am currently editing.

#### Expected Behavior

It should translate the route schema using the template language.

#### Steps to Reproduce

I used the following route schema config:

```yaml
sulu_route:
    mappings:
        Sulu\Bundle\ArticleBundle\Document\ArticleDocument:
            generator: "template"
            options:
                subjects: "/{translator.trans('app.routes.article.subjects')}/{object.getTitle()}"
```

You will need to configure the rest of the article bundle. Use different translations for en and de route!
Then set your system language to `en`.
Next you need to add a new article in the language `de`.
After saving it will show the route schema for en which should not be the case.
