### ISSUE TITLE
elasticSearch 7.9.1 (current) does not work with the SuluArticleBundle

### ISSUE THREAD

**Issue by dirkkredler** [sulu/SuluArticleBundle#517]
| Bug
| SuluArticleBundle Version | 2.1.2
| Sulu Version | Sulu (2.1.2)

#### Actual Behavior

The SuluArticleBundle does not work with  elasticSearch 7.9.1: 
Articles could not be deleted, nor used as smart content in a twig template.

#### Expected Behavior

The SuluArticleBundle should work with elasticSearch 7.9.1

#### Steps to Reproduce

- Create a fresh sulu installation `composer create-project sulu/skeleton my-project -n`
- Setup the installation and 
- Setup elasticSearch
`docker pull docker.elastic.co/elasticsearch/elasticsearch:7.9.1` and execute 
`docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.9.1`
- Add the SuluArticleBundle `composer require sulu/article-bundle`
- Create one or more articles
- Now try to delete an article (impossible)
- Now try to use the articles as smart content and process them in a twig template: the articles result array is always empty

#### Possible Solutions

Downgrade elasticSearch to 7.7.0
`docker pull docker.elastic.co/elasticsearch/elasticsearch:7.7.0` and
`docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.7.0`

everything works as expected.

**Comment by nnatter** [comment]
Hey, thank you for creating this issue. I have just tested the bundle with the following `docker-compose` config and did not encounter any problems. Deleting articles and the `smart_content` provider works like expected for me.
```
    elasticsearch:
        image: elasticsearch:7.9.1
        ports:
            - ${DOCKER_ES_PORT:-9200}:9200
        volumes:
            - ./var/data/elasticsearch:/usr/share/elasticsearch/data:cached
        environment:
            discovery.type: single-node
            xpack.security.enabled: "false"
```

Is is possible that you installed an incompatible version of the `elasticsearch/elasticsearch` package? The installed version should match the version of your ElasticSearch installation:
https://github.com/sulu/SuluArticleBundle/blob/master/Resources/doc/installation.md#install-dependencies
