### ISSUE TITLE
Elastic search limited to 10.000 entries

### ISSUE THREAD

**Issue by hgiesenow** [sulu/SuluArticleBundle#599]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| SuluArticleBundle Version | Specific version or SHA of a commit
| Sulu Version | Specific version or SHA of a commit

#### Actual Behavior

When using ElasticSearch 7.x and increasing `index.max_result_window` to 20.000 there are still only 10.000 entries displayed in backend.

#### Expected Behavior

20.000 entries should be displayed.

#### Steps to Reproduce

* Use ElasticSearch 7.x
* Create 10.001 articles
* Set index.max_result_window to 20.000
```
ongr_elasticsearch:
    managers:
        default:
            index:
                settings:
                    max_result_window: 20000
        live:
            index:
                settings:
                    max_result_window: 20000
```

#### Possible Solutions

In ElasticSearch 7.x there is a new search parameter `track_total_hits`. It must just be set to true in the query.
